parameters:

    #
    # Event Listeners
    #
    store.core.event_listener.store_disabled.class: Elcodi\Store\CoreBundle\EventListener\StoreUnavailableEventListener
    store.core.event_listener.store_under_construction.class: Elcodi\Store\CoreBundle\EventListener\StoreUnavailableEventListener
